dist: trusty
language: node_js
node_js:
  - "8"
before_script:
  - truffle version
cache:
  yarn: true
env:
  -
  - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
script:
  - yarn lint:all
  - yarn test
