dist: trusty
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
before_script:
  - truffle version
script:
  - npm run lint
  - npm run lint:sol
  - scripts/test.sh
  - SOLIDITY_COVERAGE=true scripts/test.sh
